### PR TITLE
Search bar Functionality Issue #19

### PR DESCRIPTION
**Pull request by Inventor77**

### CODE REVIEW

**Comment by Inventor77** [comment]
@sairish2001 Sir I have listed  below are some topics which will occur in Drop down, will you guide me some changes you want 


## ***Linear Algebra***
	Matrix

## ***Calculus***
	Integration
	Differentiation
	Partial Differentiation
	Laplace Transform

## ***Trigonometry***
	Trigonometry

# ***Graphs and Shapes***
	Graph Plotting
	Shapes Calculator

## ***Equations***
	Roots of Equations

## ***General Maths***
	Simple Intrest And Compound Intrest
	LCM, HCF and Factors
	Factorial
	Permutation And Combinations
	Mean, Median and Mode
	Arthmetic Progression
	Logorithmic Value

## ****Conversion Tools****

**Comment by rajinderpalsingh2001** [comment]
Where you made changes?

**Comment by Inventor77** [comment]
> Where you made changes?

@sairish2001 sir I have not made any changes in files just , I asking about the list I have commented before

**Comment by rajinderpalsingh2001** [comment]
Everything is fine

**Pull request closed without merging**
