### PR TITLE
Readme file enhanced

### PR DESCRIPTION
**Pull request by anirudhsai20**
I have added these sctions to the Readme file:
1. Introduction
2. Table of contents
3. Programming languages and technologies used
4. How to get started with Open Source
5. Contributing guidelines
6. Want to contribute?
7. Open Source programs
8. License
9. Contributors table

### CODE REVIEW

**Comment by anirudhsai20** [comment]
Hi @sairish2001. Please check if you are satisfied with the Readme file. If not, please inform me what to add in the Readme file.

**Comment by rajinderpalsingh2001** [comment]
Remove the line, which targets books.

**Comment by anirudhsai20** [comment]
Hi @sairish2001. I have made the necessary changes.

**Review by rajinderpalsingh2001 — APPROVED** [review]

**Review by rajinderpalsingh2001 — APPROVED** [review]
Well Done :)

**Pull request merged**
