### PR TITLE
Added #heading2 to all the conversion tools

### LINKED ISSUE #66: In conversion tools, Problem in differentiating different tools
Tools name should be `bold` and `text-size` should be different from all other content. 
Kindly assign me this issue

### PR DESCRIPTION
**Pull request by shonali2600**
closes #66

### CODE REVIEW

**Comment by rajinderpalsingh2001** [comment]
@shonali2600 The conflicts for both PR's are very confusing, I am unable to configure the right changes

**Comment by shonali2600** [comment]
Okay I'll make another PR for both

**Comment by shonali2600** [comment]
@sairish2001 the conflicts have been resolved now. But I think someone else has already made the changes because the recent commit is not showing the changes I made earlier.
Not sure :(

**Comment by shonali2600** [comment]
@sairish2001 same in this PR
You can view the changes that I made using this commit ` 55df5ec `

**Pull request merged**
