### PR TITLE
Dark/Light mode added

### LINKED ISSUE #36: Adding Dark-light Mode
I want to add dark/light mode to the website  as GSSOC'21 participant .
Please assign me this issue.

### PR DESCRIPTION
**Pull request by Bhavya-Sehgal**
Fixed #36 
Added Dark/Light Mode

Screenshots:
Light mode:

lightmode

Dark mode:

darkmode
 
Please view my PR @sairish2001

### CODE REVIEW

**Comment by robinsingh-ai** [comment]
@Bhavya-Sehgal  this enhancement looks really good and thanks for solving the navbar issue

**Comment by rajinderpalsingh2001** [comment]
@Bhavya-Sehgal Great
But please don't use pure black, use the same color for dark mode as used in Main Project

**Comment by Bhavya-Sehgal** [comment]
I have changed the color @sairish2001. Now give it a look

**Comment by rajinderpalsingh2001** [comment]
Please Provide a screenshot

**Comment by Bhavya-Sehgal** [comment]
darknew

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 

darknew

**Review by rajinderpalsingh2001 — APPROVED** [review]

**Pull request merged**
